# Generated by Django 5.2.6 on 2026-03-25 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='部門名稱')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='員工編號')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女'), ('O', '其他')], max_length=1, verbose_name='性別')),
                ('birthday', models.DateField(verbose_name='出生日期')),
                ('id_number', models.CharField(max_length=10, verbose_name='身份證字號')),
                ('phone', models.CharField(max_length=20, verbose_name='聯絡電話')),
                ('address', models.TextField(verbose_name='地址')),
                ('emergency_contact', models.CharField(max_length=50, verbose_name='緊急聯絡人姓名')),
                ('emergency_phone', models.CharField(max_length=20, verbose_name='緊急聯絡人電話')),
                ('job_title', models.CharField(max_length=100, verbose_name='職稱')),
                ('emp_type', models.CharField(choices=[('full_time', '全職'), ('part_time', '兼職'), ('intern', '實習')], default='full_time', max_length=20, verbose_name='員工類型')),
                ('status', models.CharField(choices=[('active', '在職'), ('resigned', '離職'), ('on_leave', '留停')], default='active', max_length=20, verbose_name='員工狀態')),
                ('hire_date', models.DateField(verbose_name='到職日')),
                ('resignation_date', models.DateField(blank=True, null=True, verbose_name='離職日')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.department', verbose_name='部門')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee', verbose_name='直屬主管')),
            ],
        ),
    ]
