# Generated by Django 6.0.4 on 2026-04-10 02:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_auth_and_self_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimerecord',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='核准時間'),
        ),
        migrations.AddField(
            model_name='overtimerecord',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_overtime_records', to='employees.employee', verbose_name='核准主管'),
        ),
        migrations.AddField(
            model_name='overtimerecord',
            name='auto_approved',
            field=models.BooleanField(default=False, verbose_name='是否自動核准'),
        ),
        migrations.AddField(
            model_name='overtimerecord',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='申請時間'),
            preserve_default=False,
        ),
    ]
