# django
FROM ubuntu:22.04
LABEL maintainer="roiz <qqa123456408@gmail.com>"
LABEL version="1.0"
LABEL description="測試並學習dockerfile"

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    DEBIAN_FRONTEND=noninteractive

WORKDIR /app

# 安裝 Python 和 ODBC 驅動
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3.11 \
    python3-pip \
    curl \
    gnupg2 \
    unixodbc \
    unixodbc-dev \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -y --no-install-recommends msodbcsql18 \
    && rm -rf /var/lib/apt/lists/*

COPY HR_system/requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt
# 複製後端代碼
COPY HR_system/ .


CMD [ "python3","manage.py","runserver","0.0.0.0:8000"]